baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: My website
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://styles.redditmedia.com/t5_3pgxe/styles/communityIcon_el7t4q1csw321.jpg?width=256&format=pjpg&s=e95c28f0e06d523c6122a609492106d7c5e50f20
          weight: 6

params:
    description: "My name is Dante, I am a second-year high schooler at Port Credit Secondary School. I am in the Scitech regional program so I have lots of knowledge based on science and technology courses, I am very strong in most things with technology and have some strengths in science-related fields. "
    author: Dante
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: About Dante
          subtitle: "My name is Dante, I am a second-year high schooler at Port Credit Secondary School. I am in the Scitech regional program so I have lots of knowledge based on science and technology courses, I am very strong in most things with technology and have some strengths in science-related fields."
          imageUrl: "https://styles.redditmedia.com/t5_3pgxe/styles/communityIcon_el7t4q1csw321.jpg?width=256&format=pjpg&s=e95c28f0e06d523c6122a609492106d7c5e50f20"
          imageWidth: 160
          imageHeight: 160
          buttons:
          url: 
          Papers
        	- name: 
          	url: 
        	- name: 
          	url: 
        	- name: 
          	url: 
        	- name: 
          	url: 
        	- name: 
          	url: 
        	- name: 
         
 

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: 
          url: 
          URL: 
        - name: 
          url: 
        - name: 
          url: 
        - name: 
          url: 
        - name: GitHub
          url: https://github.com/Danteg109
        - name: 
          url: 
        - name: 
          url: 
        - name: 
          url: 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: 
      icon: 
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
